// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Bank = "Bank",
  Cactus = "Cactus",
  Cactus_4 = "Cactus 4",
  Cactus_4_2 = "Cactus 4_2",
  Cactus_4_3 = "Cactus 4_3",
  Cactus_4_4 = "Cactus 4_4",
  Cactus_4_5 = "Cactus 4_5",
  Cactus_4_6 = "Cactus 4_6",
  Cactus_4_7 = "Cactus 4_7",
  Cactus_4_8 = "Cactus 4_8",
  Carreta = "Carreta",
  Carreta_2 = "Carreta_2",
  For_Code = "For_Code",
  House_5_M_Blue = "House 5 M Blue",
  House_5_M_Blue_2 = "House 5 M Blue_2",
  House_5_M_Blue_3 = "House 5 M Blue_3",
  House_5_M_Blue_4 = "House 5 M Blue_4",
  House_5_M_Blue_5 = "House 5 M Blue_5",
  House_7_M_Blue = "House 7 M Blue",
  House_7_M_Blue_2 = "House 7 M Blue_2",
  House_7_M_Blue_3 = "House 7 M Blue_3",
  House_7_M_Blue_4 = "House 7 M Blue_4",
  House_7_M_Blue_5 = "House 7 M Blue_5",
  Layout = "Layout",
  MULE = "MULE",
  Market = "Market",
  Mining_Area = "Mining_Area",
  Mule_Area = "Mule_Area",
  Railway = "Railway",
  Rustic_Wheelbarrow = "Rustic Wheelbarrow",
  Text = "Text",
  Text_2 = "Text_2",
  Town_Mayor = "Town Mayor",
  Train_Track_6_M_Old_V01 = "Train Track 6 M Old V01",
  Train_Track_6_M_Old_V01_2 = "Train Track 6 M Old V01_2",
  Train_Track_6_M_Old_V01_3 = "Train Track 6 M Old V01_3",
  Train_Track_6_M_Old_V01_4 = "Train Track 6 M Old V01_4",
  Train_Track_6_M_Old_V01_5 = "Train Track 6 M Old V01_5",
  Train_Track_6_M_Old_V01_6 = "Train Track 6 M Old V01_6",
  monument_glb = "monument.glb",
} 
